name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:


jobs:

  pull:

    runs-on: [self-hosted, backup, main]


    steps:

      - name: Pull from repo
        run: cd /var/www/waxes27.com/; git pull;php artisan migrate:fresh

