name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:


jobs:

  pull:

    runs-on: self-hosted


    steps:

      - name: Pull from repo
        run: cd /var/www/waxes27.com/; git stash; git pull
        
  migration:
  
    runs-on: self-hosted
    steps:
      - name: migrations
        run: cd /var/www/waxes27.com/; php artisan migrate:fresh

